runtime: python
env: flex
network:
    session_affinity: true
manual_scaling:
    instances: 1
#https://cloud.google.com/appengine/docs/flexible/python/runtime 
runtime_config:
      operating_system: "ubuntu22"
